---
apiVersion: v1
kind: Service
metadata:
  name: phnumbers
spec:
  ports:
  - protocol: TCP
    port: 9000
  selector:
    app: phnumbers

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phnumbers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phnumbers
  template:
    metadata:
      labels:
        app: phnumbers
    spec:
      containers:
        - name: phnumbers
          image: thepreacher/phnumbers:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
